debpkg: update config and dont auto-start if not enabled

diff --git a/contrib/debpkg/aquachain.postinst b/contrib/debpkg/aquachain.postinst
--- a/contrib/debpkg/aquachain.postinst
+++ b/contrib/debpkg/aquachain.postinst
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # this is a postinst script for aquachain debian package
 # we make systemd unit, user, group, and config files
 set -e
@@ -12,7 +12,7 @@ fi
 now=$(date)
 default_aqua_homedir=/var/lib/aquachain
 
-# Source the configuration values.
+# Source the configuration values if they already exist
 if [ -f /etc/aquachain/aquachain.conf ]; then
     . /etc/aquachain/aquachain.conf
 else
@@ -21,7 +21,7 @@ else
 fi
 
 echo "Aquachain installed successfully."
-echo "Coinbase Address: $AQUABASE"
+echo "Coinbase Address: ${AQUABASE-none}"
 echo "Data Directory: $AQUACHAIN_DATADIR"
 echo "Chain: $AQUACHAIN_CHAIN"
 echo "Verbosity: $VERBOSITY"
@@ -33,30 +33,35 @@ if [ ! -d $default_aqua_homedir ]; then
     echo "aqua homedir not found, creating it: $default_aqua_homedir"
     mkdir -v -p $default_aqua_homedir
     chown -v -R aqua:aqua $default_aqua_homedir
-    chmod -v 700 $default_aqua_homedir
+    chmod -v 750 $default_aqua_homedir
     echo "created aqua directory: $default_aqua_homedir"
 fi
 
 # rare
-if [ -d /etc/default ]; then
+if [ ! -d /etc/default ]; then
     mkdir -p /etc/default
 fi
 
-# create system env file
+# create system env file if not exist
 test -f /etc/default/aquachain || cat >/etc/default/aquachain <<EOF2
 # aquachain config (generated by dpkg ${now})
 # this env file is used by the systemd service
 JSONLOG=0
 NO_SIGN=1
 NO_KEYS=1
+COLOR=1
 EOF2
 chmod -v 644 $tmpdir/etc/default/aquachain
 
 # enable and start the service
 
-echo "aquachain is installed, now starting it"
+# echo "aquachain is installed, now starting it"
 systemctl daemon-reload || true
-systemctl enable --now aquachain || service aquachain start || echo "warn: failed to start aquachain service"
-
+# systemctl enable --now aquachain || service aquachain start || echo "warn: failed to start aquachain service"
+# restart if already running
+if systemctl is-active --quiet aquachain; then
+    systemctl daemon-reload
+    systemctl restart aquachain
+fi
 echo "done installing aquachain"
 exit 0
